"""empty message

Revision ID: e2d3ab25c9fa
Revises: 833724243ce0
Create Date: 2022-08-25 12:13:38.776666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d3ab25c9fa'
down_revision = '833724243ce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bags', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bags', 'title')
    # ### end Alembic commands ###
